FKSC_v2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('inicial.urls')),
    url(r'^filiados/', include('filiados.urls')),
    url(r'^campeonatos/', include('campeonatos.urls')),
    url(r'^videos/', include('videos.urls')),
    url(r'^ranking/', include('ranking.urls')),
    url(r'^convocados/', include('convocados.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campeonatos/urls.py
from django.conf.urls import url
from . import views

app_name = 'campeonatos'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

convocados/urls.py
from django.conf.urls import url
from . import views

app_name = 'convocados'

urlpatterns = [
    # /convocados/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /convocados/3
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

filiados/urls.py
from django.conf.urls import url
from . import views

app_name = 'filiados'

urlpatterns = [
    # /filiados/
    url(r'^$', views.index, name='index'),

    # /filiados/academias/
    url(r'^academias/$', views.academias, name='academias'),

    # /filiados/atletas/
    url(r'^atletas/$', views.atletas, name='atletas'),

    # /filiados/pretas/
    url(r'^pretas/$', views.pretas, name='pretas'),
]

inicial/urls.py
from django.conf.urls import url
from . import views

app_name = 'inicial'

urlpatterns = [
    #
    url(r'^$', views.index, name='index'),
]

ranking/urls.py
from django.conf.urls import url
from . import views

app_name = 'ranking'

urlpatterns = [
    # /ranking/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /ranking/3
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

videos/urls.py
from django.conf.urls import url
from . import views

app_name = 'videos'

urlpatterns = [
    # /videos/
    url(r'^$', views.index, name='index'),
]

campeonatos/models.py
from django.db import models

class Campeonato(models.Model):
    nome_campeonato = models.CharField(max_length=400)
    est_cidade = models.CharField(max_length=100)
    data = models.CharField(max_length=50)
    endereco = models.CharField(max_length=500)
    cartaz = models.FileField(default='/static/images/logo.jpg')

    def __str__(self):
        return self.nome_campeonato

convocados/models.py
from django.db import models

class Convocado_campeonato(models.Model):
    nome_campeonato = models.CharField(max_length=400)
    est_cidade = models.CharField(max_length=100)
    data = models.CharField(max_length=50)
    cartaz = models.FileField(default='/static/images/logo.jpg')

    def __str__(self):
        return self.nome_campeonato

class Convocados(models.Model):
    Convocado_campeonato = models.ForeignKey(Convocado_campeonato, on_delete=models.CASCADE)
    nome = models.CharField(max_length=500)
    academia = models.CharField(max_length=200)
    faixa = models.CharField(max_length=100)
    reg_fed = models.IntegerField()

    def __str__(self):
        return self.nome

filiados/models.py
from django.db import models

class Academia(models.Model):
    professor = models.CharField(max_length=100)
    nome_academia = models.CharField(max_length=200)
    estado = models.CharField(max_length=50)
    cidade = models.CharField(max_length=50)
    rua = models.CharField(max_length=200)
    bairro = models.CharField(max_length=200)
    cep = models.IntegerField()
    num_reg = models.IntegerField()

    def __str__(self):
        return self.nome_academia +' - '+ self.cidade

class Atleta(models.Model):
    nome_atleta = models.CharField(max_length=100)
    academia = models.CharField(max_length=200)
    num_reg = models.IntegerField()

    def __str__(self):
        return self.nome_atleta

class Preta(models.Model):
    nome_preta = models.CharField(max_length=100)
    academia = models.CharField(max_length=200)
    num_reg = models.IntegerField()

    def __str__(self):
        return self.nome_preta

inicial/models.py
from django.db import models

# Create your models here.

ranking/models.py
from django.db import models

class Rank_campeonato(models.Model):
    nome_campeonato = models.CharField(max_length=400)
    est_cidade = models.CharField(max_length=100)
    data = models.CharField(max_length=50)
    cartaz = models.FileField(default='/static/images/logo.jpg')

    def __str__(self):
        return self.nome_campeonato

class Categoria(models.Model):
    rank_campeonato = models.ForeignKey(Rank_campeonato, on_delete=models.CASCADE)
    idade = models.CharField(max_length=100)
    faixa = models.CharField(max_length=100)
    sexo = models.CharField(max_length=50)
    modalidade = models.CharField(max_length=50)
    primeiro = models.CharField(max_length=200)
    acad_primeiro = models.CharField(max_length=200)
    segundo = models.CharField(max_length=200,default='None')
    acad_segundo = models.CharField(max_length=200,default='None')
    terceiro = models.CharField(max_length=200,default='None')
    acad_terceiro = models.CharField(max_length=200,default='None')

    def __str__(self):
        return self.idade +'/'+ self.faixa +'/'+ self.sexo +'/'+ self.modalidade

videos/models.py
from django.db import models

class Video(models.Model):
    titulo = models.CharField(max_length=200)
    link = models.CharField(max_length=500)

    def __str__(self):
        return self.titulo

campeonatos/views.py
from django.shortcuts import render
from django.views import generic
from .models import Campeonato

class IndexView(generic.ListView):
    template_name = 'campeonatos/index.html'
    context_object_name = 'todos_campeonatos'

    def get_queryset(self):
        return Campeonato.objects.all()

convocados/views.py
from django.views import generic
from .models import Convocado_campeonato

class IndexView(generic.ListView):
    template_name = 'convocados/index.html'
    context_object_name = 'todos_campeonatos'

    def get_queryset(self):
        return Convocado_campeonato.objects.all()

class DetailView(generic.DetailView):
    model = Convocado_campeonato
    template_name = 'convocados/detail.html'

filiados/views.py
from .models import Academia, Atleta, Preta
from django.shortcuts import render

def index(request):
    return render(request, 'inicial/index.html')

def ordenar_num(lista):
    for i in range(0,len(lista)):
        for j in range(i,len(lista)):
            if lista[i] >= lista[j]:
                lista[i], lista[j] = lista[j], lista[i]
    return lista

def ordenar(todas_academias):
    lista = []
    for academia in todas_academias:
        lista = lista + [academia.num_reg]
    num_organizados = ordenar_num(lista)
    nova_lista_academias = []
    for reg in num_organizados:
        for academia in todas_academias:
            if reg == academia.num_reg:
                nova_lista_academias = nova_lista_academias + [academia]
    return nova_lista_academias

def academias(request):
    todas_academias = Academia.objects.all()
    return render(request,'filiados/academias.html', {'todas_academias': ordenar(todas_academias)})

def atletas(request):
    todos_atletas = Atleta.objects.all()
    return render(request, 'filiados/atletas.html', {'todos_atletas': ordenar(todos_atletas)})

def pretas(request):
    todos_pretas = Preta.objects.all()
    return render(request, 'filiados/pretas.html', {'todos_pretas': ordenar(todos_pretas)})

inicial/views.py
from django.shortcuts import render

def index(request):
    return render(request,'inicial/index.html')

ranking/views.py
from django.views import generic
from .models import Rank_campeonato

class IndexView(generic.ListView):
    template_name = 'ranking/index.html'
    context_object_name = 'todos_campeonatos'

    def get_queryset(self):
        return Rank_campeonato.objects.all()

class DetailView(generic.DetailView):
    model = Rank_campeonato
    template_name = 'ranking/detail.html'

videos/views.py
from django.shortcuts import render
from .models import Video

def index(request):
    todos_videos = Video.objects.all()
    return render(request, 'videos/index.html', {'todos_videos': todos_videos})

convocados/templates/convocados/detail.html
{% extends 'inicial/base.html' %}
{% block head %}{% load staticfiles %}{% endblock %}
{% block body %}
            <!--========== PROMO BLOCK ==========-->
        <div class="s-promo-block-v3 g-bg-position--center g-fullheight--sm" style="background: url('{% static 'inicial/HTML/img/1920x1080/blackbelt.jpg' %}');">
            <div class="container g-ver-center--sm g-padding-y-125--xs g-padding-y-0--sm">
                <div class="g-margin-t-30--xs g-margin-t-0--sm g-margin-b-30--xs g-margin-b-70--md">
                    <h1 class="g-font-size-35--xs g-font-size-45--sm g-font-size-50--lg g-color--white">IX Copa da Paz<br>Mundial de Artes Marciais</h1>
                </div>
                <div class="row">
                    <div class="col-sm-8 col-sm-push-4 g-margin-b-50--xs g-margin-b-0--md">
                        <div class="s-promo-block-v3__divider g-display-none--xs g-display-block--md"></div>
                        <div class="row">
                            <div class="col-sm-6 g-margin-b-30--xs g-margin-b-0--md">
                                <div class="wow fadeInLeft" data-wow-duration=".3" data-wow-delay=".4s">
                                    <p class="g-font-size-18--xs g-color--white-opacity">Venha participar ou assitir esse combate entre os melhores atletas do ano, um Campeonato Internacional na nossa região, Anápolis-GO, no Ginásio Internacional Newton de Faria.</p>
                                </div>
                            </div>
                            <div class="col-sm-5 col-sm-offset-1">
                                <div class="clearfix">
                                    <div class="pull-left">
                                        <div class="wow fadeInLeft" data-wow-duration=".3" data-wow-delay=".3s">
                                            <span class="s-promo-block-v3__date g-font-size-100--xs g-font-size-135--lg g-font-weight--300 g-color--primary">28/29</span>
                                        </div>
                                    </div>
                                    <div class="wow fadeInLeft" data-wow-duration=".3" data-wow-delay=".1s">
                                        <span class="s-promo-block-v3__month g-font-size-18--xs g-font-size-22--lg g-font-weight--300 g-color--white-opacity-light">Out</span>
                                        <span class="s-promo-block-v3__year g-font-size-18--xs g-font-size-22--lg g-font-weight--300 g-color--white-opacity-light">2017</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4 col-sm-pull-8">
                        <div class="wow fadeInLeft" data-wow-duration=".3" data-wow-delay=".5s">
                            <a class="js__popup__youtube" href="https://www.youtube.com/channel/UCY7WvojM2d1-4qNf_cO7Ezg" title="Videos da FKSC">
                                <i class="s-icon s-icon--lg s-icon--white-bg g-radius--circle ti-control-play"></i>
                                <span class="text-uppercase g-font-size-13--xs g-color--white g-padding-x-15--xs">Assita o Trailer</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--========== END PROMO BLOCK ==========-->

        <!--========== PAGE CONTENT ==========-->
        <!-- Inicio dos Convocados -->
    <br><br>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="panel panel-default"
             <div class="panel-body">
                 <h3>Atletas Convocados - 2017</h3>
                 <table class="table">
                     <thead>
                     <tr>
                         <th>Nome</th>
                         <th>Academia</th>
                         <th>Faixa</th>
                         <th>Número de Registro</th>
                     </tr>
                     </thead>
                     <tbody>
                     {% for atleta in convocado_campeonato.convocados_set.all %}
                     <tr>
                         <td>{{ atleta.nome }}</td>
                         <td>{{ atleta.academia }}</td>
                         <td>{{ atleta.faixa }}</td>
                         <td>{{ atleta.reg_fed }}</td>
                     </tr>
                     {% endfor %}
                     </tbody>
                 </table>
             </div>
        </div>
    </div>
    <br><br><br><br>
        <!-- Final dos Convocados -->

   <!-- Features -->
   <div id="js__scroll-to-section" class="container g-padding-y-80--xs g-padding-y-125--sm">
            <div class="row g-margin-b-60--xs g-margin-b-70--md">
                <div class="col-sm-4 g-margin-b-60--xs g-margin-b-0--md">
                    <div class="clearfix">
                        <div class="g-media g-width-30--xs">
                            <div class="wow fadeInDown" data-wow-duration=".3" data-wow-delay=".1s">
                                <a href="{% url 'filiados:academias' %}"> <i class="g-font-size-28--xs g-color--primary ti-home"></i></a>
                            </div>
                        </div>
                        <div class="g-media__body g-padding-x-20--xs">
                            <a href="{% url 'filiados:academias' %}"> <h3 class="g-font-size-18--xs">Academias Filiadas 2017</h3></a>
                            <p class="g-margin-b-0--xs">Essa é a lista das Academias que são nossas afiliadas.</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 g-margin-b-60--xs g-margin-b-0--md">
                    <div class="clearfix">
                        <div class="g-media g-width-30--xs">
                            <div class="wow fadeInDown" data-wow-duration=".3" data-wow-delay=".2s">
                                <a href="{% url 'filiados:atletas' %}"> <i class="g-font-size-28--xs g-color--primary ti-agenda"></i></a>
                            </div>
                        </div>
                        <div class="g-media__body g-padding-x-20--xs">
                            <a href="{% url 'filiados:atletas' %}"><h3 class="g-font-size-18--xs">Atletas Filiados 2017</h3></a>
                            <p class="g-margin-b-0--xs">Essa é a lista dos Atletas que são nossos afiliados.</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="clearfix">
                        <div class="g-media g-width-30--xs">
                            <div class="wow fadeInDown" data-wow-duration=".3" data-wow-delay=".3s">
                                <a href="{% url 'filiados:pretas' %}"> <i class="g-font-size-28--xs g-color--primary ti-plus"></i></a>
                            </div>
                        </div>
                        <div class="g-media__body g-padding-x-20--xs">
                            <a href="{% url 'filiados:pretas' %}"><h3 class="g-font-size-18--xs">Faixas Pretas</h3></a>
                            <p class="g-margin-b-0--xs">Essa é a lista do registro de todos Faixas Pretas desde 1996.</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- // end row  -->
            <div class="row">
                <div class="col-sm-4 g-margin-b-60--xs g-margin-b-0--md">
                    <div class="clearfix">
                        <div class="g-media g-width-30--xs">
                            <div class="wow fadeInDown" data-wow-duration=".3" data-wow-delay=".4s">
                                <a href="{% url 'campeonatos:index' %}"> <i class="g-font-size-28--xs g-color--primary ti-medall"></i></a>
                            </div>
                        </div>
                        <div class="g-media__body g-padding-x-20--xs">
                            <a href="{% url 'campeonatos:index' %}"><h3 class="g-font-size-18--xs">Circuito Competitivo 2017</h3></a>
                            <p class="g-margin-b-0--xs">Essa é a lista de todos os nossos Campeonatos.</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 g-margin-b-60--xs g-margin-b-0--md">
                    <div class="clearfix">
                        <div class="g-media g-width-30--xs">
                            <div class="wow fadeInDown" data-wow-duration=".3" data-wow-delay=".5s">
                                <a href="{% url 'ranking:index' %}"> <i class="g-font-size-28--xs g-color--primary ti-star"></i></a>
                            </div>
                        </div>
                        <div class="g-media__body g-padding-x-20--xs">
                            <a href="{% url 'ranking:index' %}"><h3 class="g-font-size-18--xs">Ranking 2017</h3></a>
                            <p class="g-margin-b-0--xs">Aqui está o Ranking de cada Campeonato, o Ranking Geral e o Ranking das Academias.</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="clearfix">
                        <div class="g-media g-width-30--xs">
                            <div class="wow fadeInDown" data-wow-duration=".3" data-wow-delay=".6s">
                                <a href="{% url 'videos:index' %}"> <i class="g-font-size-28--xs g-color--primary ti-video-camera"></i></a>
                            </div>
                        </div>
                        <div class="g-media__body g-padding-x-20--xs">
                            <a href="{% url 'videos:index' %}"><h3 class="g-font-size-18--xs">Vídeos</h3></a>
                            <p class="g-margin-b-0--xs">Aqui você encontrará vídeos de Kumitê, Kata, Kobudô, Artes Marciais e muito mais.</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- // end row  -->
        </div>
        <!-- End Features -->


        <!-- Parceiros -->
        <div class="g-padding-y-80--xs g-padding-y-125--sm">
            <div class="g-container--sm">
                <div class="g-text-center--xs g-margin-b-80--xs">
                    <h2 class="g-font-size-32--xs g-font-size-36--sm">Parceiros - Federações que somos Filiados</h2>
                    <p class="g-font-size-18--md">Agradecemos as Federações que somos Filiados Nacionalmente e Internacionalmente. Aos Parceiros e as Prefeituras que fazem o campeonato possível.</p>
                </div>
            </div>
            <div class="g-container--md">
                <!-- Swiper Clients -->
                <div class="s-swiper js__swiper-clients">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide">
                            <div class="wow fadeIn" data-wow-duration=".3" data-wow-delay=".1s">
                                <img class="s-clients-v1" src="{% static 'inicial/HTML/img/clients/cbksc1.png' %}" alt="Logo Parceiros">
                            </div>
                        </div>
                        <div class="swiper-slide">
                            <div class="wow fadeIn" data-wow-duration=".3" data-wow-delay=".2s">
                                <img class="s-clients-v1" src="{% static 'inicial/HTML/img/clients/skif.png' %}" alt="Logo Parceiros">
                            </div>
                        </div>
                        <div class="swiper-slide">
                            <div class="wow fadeIn" data-wow-duration=".3" data-wow-delay=".3s">
                                <img class="s-clients-v1" src="{% static 'inicial/HTML/img/clients/wtmf.png' %}" alt="Logo Parceiros">
                            </div>
                        </div>
                        <div class="swiper-slide">
                            <div class="wow fadeIn" data-wow-duration=".3" data-wow-delay=".4s">
                                <img class="s-clients-v1" src="{% static 'inicial/HTML/img/clients/mafwp.png' %}" alt="Logo Parceiros">
                            </div>
                        </div>
                        <div class="swiper-slide">
                            <div class="wow fadeIn" data-wow-duration=".3" data-wow-delay=".5s">
                                <img class="s-clients-v1" src="{% static 'inicial/HTML/img/clients/wpmaf.png' %}" alt="Logo Parceiros">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Swiper Clients -->
            </div>
        </div>
        <!-- End Clients -->

    <!-- Google Map -->
    <div class="map-responsive">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d451.7482656298398!2d-48.97235195175308!3d-16.328825864283647!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x935ea39046038e8f%3A0x37f91ba3864d6454!2sR.+Luciano+Carneiro%2C+1+-+Vila+Calixto+Abrao%2C+An%C3%A1polis+-+GO%2C+75144-460!5e0!3m2!1spt-BR!2sbr!4v1509109576857" width="1600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
    <!-- End Google Map -->
        <!--========== END PAGE CONTENT ==========-->



{% endblock %}

filiados/templates/filiados/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}FKSC-GO{% endblock  %}</title>
    <link rel="icon" type="image/png" href="{% static 'images/logo.png' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel='stylesheet' href='{% static "css/estilo.css" %}'/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {% block head %}
    {% endblock %}
</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- brand -->
            <a class="navbar-brand" href="{% url 'inicial:index' %}">FKSC-GO</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class=""><a href="{% url 'inicial:index' %}">Página Inicial</a></li>
                <li class="dropdown">
                    <a href="{% url 'campeonatos:index' %}" class="dropdown-toggle" data-toggle="dropdown">Campeonatos <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'campeonatos:index' %}">Campeonatos 2017</a></li>
                        <li><a href="{% url 'convocados:index' %}">Convocações</a></li>
                    </ul>
                </li>
                <!-- Dropdown Menu-->
                <li class="dropdown">
                    <a href="{% url 'filiados:index' %}" class="dropdown-toggle" data-toggle="dropdown">Filiados <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'filiados:academias' %}">Academias</a> </li>
                        <li><a href="{% url 'filiados:atletas' %}">Atletas</a> </li>
                        <li><a href="{% url 'filiados:pretas' %}">Faixas Pretas</a> </li>
                    </ul>
                </li>
                <li class=""><a href="{% url 'ranking:index' %}">Ranking</a></li>
                <li class=""><a href="{% url 'videos:index' %}">Videos</a></li>
                <li class=""><a href="#">Contato</a> </li>
            </ul>
        </div>
    </div>
</nav>


{% block body %}
{% endblock %}

<!-- Footer -->
<div id="footer">
    <p class="muted credit">Todos os direitos reservados<span class="glyphicon glyphicon-copyright-mark"></span>1996 - 2017 Federação de Karatê Semi
        Contato do Estado de Goiás (FKSC-GO)</p>
</div>

</body>
</html>

filiados/templates/filiados/index.html
{% extends 'filiados/base.html' %}
{% block head %}{% load staticfiles %}{% endblock %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="thumbnail">
                <a href="{% url 'filiados:academias' %}">
                    <img src='{% static "images/logo.jpg" %}' class="img-responsive">
                </a>
                <div class="caption">
                    <h2><a href="{% url 'filiados:academias' %}">Academias Filiadas</a></h2>
                    <h4>2017</h4>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="thumbnail">
                <a href="{% url 'filiados:atletas' %}">
                    <img src='{% static "images/at2.jpg" %}' class="img-responsive">
                </a>
                <div class="caption">
                    <h2><a href="{% url 'filiados:atletas' %}">Atletas Filiados</a></h2>
                    <h4>2017</h4>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="thumbnail">
                <a href="{% url 'filiados:pretas' %}">
                    <img src='{% static "images/preta.jpg" %}' class="img-responsive">
                </a>
                <div class="caption">
                    <h2><a href="{% url 'filiados:pretas' %}">Faixas Pretas Registrados</a></h2>
                    <h4>Desde 1996</h4>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}